import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

def send_email_report(recipient_email, df_report):
    try:
        # SMTP server configuration (example uses Gmail)
        smtp_server = "smtp.gmail.com"
        smtp_port = 587
        sender_email = "n95073@gmail.com" 
        sender_password = "123456"   
        # Convert DataFrame to CSV string
        csv_data = df_report.to_csv(index=False)
        
        # Create the email message
        message = MIMEMultipart()
        message["From"] = sender_email
        message["To"] = recipient_email
        message["Subject"] = "Your AI Resume Screener Report"
        
        # Email body
        body = "Please find attached the resume report generated by our AI Resume Screener."
        message.attach(MIMEText(body, "plain"))
        
        # Attach CSV
        attachment = MIMEText(csv_data, "csv")
        attachment.add_header("Content-Disposition", "attachment", filename="resume_report.csv")
        message.attach(attachment)
        
        # Connect to SMTP server and send email
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(message)
        server.quit()
        
        return True
    except Exception as e:
        print("Error sending email:", e)
        return False
